const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),M=require('../dist/logic.js');
const box={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'dist/data.js'),'utf8'),box);
const D=box.window.PLAN_DATA;
assert.equal(D.budget.reduce((s,b)=>s+b.total,0),1500);
for(let i=0;i<3;i++)assert.equal(D.budget.reduce((s,b)=>s+b.tranches[i],0),500);
assert.equal(D.lessons.length,58);assert.equal(D.sources.length,32);
assert.equal(M.capacity().count,8);assert.equal(M.capacity({filterCost:40}).count,6);
assert.equal(M.capacity({tax:21}).count,6);assert.equal(M.capacity({tax:21,filterCost:40}).count,4);
assert.equal(M.capacity({extraAdmin:390}).funded,false);
assert.equal(M.capacity({saving:150}).total,1500);
assert.throws(()=>M.capacity({tax:-1}));
assert.equal(M.test({spend:10,clicks:5,atc:0,purchases:0}).key,'stop');
assert.equal(M.test({spend:20,clicks:40,atc:0,purchases:0}).key,'review');
assert.equal(M.test({spend:20.01,clicks:40,atc:0,purchases:0}).key,'stop');
assert.equal(M.test({spend:30,clicks:60,atc:4,purchases:0}).key,'stop');
assert.equal(M.test({spend:30,clicks:60,atc:4,purchases:0,extended:true}).key,'review');
assert.equal(M.test().key,'continue');assert.equal(M.test({funded:false}).key,'review');
assert.equal(M.test({measured:false}).key,'review');
assert.equal(M.test({after48:true,positive:false}).key,'stop');
assert.throws(()=>M.test({clicks:1.5}));
assert(Math.abs(M.economics().contribution-7.891769421487601)<1e-8);
assert(M.economics({cpa:25}).contribution<0);
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
for(const name of ['data.js','logic.js','content.js','app.js','styles.css','documentos/Plan_inversion_Dropship_AI_Operator_1500_EUR.pdf','documentos/Hoja_ruta_ARZ_Urus_1500_EUR.pdf','documentos/presupuesto_1500.csv'])assert(fs.existsSync(path.join(root,'dist',name)),name);
assert(html.includes('lang="es"'));
console.log('OK: budget, three tranches, course/source counts, decision thresholds, tax scenarios, margin and public assets.');
